language: minimal
dist: xenial
script:
- make tests
before_deploy:
- curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
- $HOME/.poetry/bin/poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- $HOME/.poetry/bin/poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
env:
  global:
  - secure: N8CY3fzjLhkz4GiDwOidgUgKD2pSQcIJ68UDC2qegQ0VENONKjY6Rr7BDyAa49Rqy+Iv837yI7mn79rNl0bI1t6FOODj67Mm9rkIQOdFaWtVCkJmMe4Wb3lw2/DheZKBJ0UEk6KgOf+INM1AlipipxrXVYslQOcDB8RSBs2RY3n8emg+SaEWwpsW9ilgYZYNkXg8wqmOznmarJgK5Opj3nldGemTSmXAdSfKgjeCtcM3hBpNwRCBk6Lo7KPX5+XclmHqsJEQ/Oh0RvdWMhHPCZeA+pbm3D5EEiIiGOa/GPHxkvDXkBZoNEP0n1287r20UhKDzc0gM+MI8brgbPEB5LtuL7z2zRxfJh23B/9dLNR85ZWCfwDNgZHaO5x2FJfRUeoWA0mhnNEvh4WHc3pFPt4gchCBpidtjeW2lWfkUQb1QX5bawYJqHQlkw98WOpesuzua3g4fwh0ySIFN5tjXUHL5v4+Bx58z66VYPCDOR178RhRNDmeKGjnIwlormSLxH7zAkI7DMrC8C1/QqIQQJNUMA2SrFMJ2zeOXM5H2YRH5IcJhm8pVZ0zokexUlbrojnqYuqvOlhIJGB02k4HXmBBpaF9/PWO5wHmAgiOwKuNTVSSQVm2L86smkH450FCsBC6so/TDMPjhIEiEdkG83a4tOy065ym/LhcI4sgYIc=
  - secure: Ioud+EIOALZ3zMSA6oM3Y7kPlTNSqWfO8Et5H4kN7us82V0UMDQz1MTKomJYOwVB4Vi3KKoIvv5kRq62EIrYraGeiLwfihv+bPKpnEc4esKOsVNkgxTqQ/cPDLlZrYAj6Yh5F0H3vAilGytmVkZzEPyGJCwqfpl3txpqdUh4qiNK94/1LDY8VReaixwRYbac1QbE6DdRc1U0FgWJXXFoMLuSglNGEUv77lPaKOFCIPicXOE0OfgqQMJhBJQfRBN22Bw+V7yDq/oa+iYahQP90hpIiUc6GL1bPwEqQ3QKuHm2onJnqSIp7LGdU0gup2JzMqOwl3yLEAhh+n1c7xWV1SIcmCwFSTWid1WIjGrHxH18soZw0RxKB7cD2IlG2EDV+CU3bngjGghzu8kn3vM4LWy15+uD6adOl3oyrvto6XnGTSvW85MDwuaK/XroX46QTfto009dLjm/2sqteD3BXtnx29PJJbOXE2g67iKeTQVTo/qdH6t1EG966qSlba27n1WxlqYGvKok07nOcY/5xQEKTamf3Ca1tomX6YGtyitJDUKKh/jd2WTgk57aH+5iVirf4Aonr6gUF0qDLyXl74d3s2kLOhvV2Sj2MaDj14dpydEIiFVnda5Pn3UyiJTPJzp6FdoP6W33dQPRy0Ae401wbUjK9MX+ZT+ucylZSI4=
