language: python
services:
- docker
python: 3.6
script:
- make tests
before_deploy:
- pip install poetry
- poetry build
deploy:
  provider: script
  script: poetry publish -u __token__ -p $PYPI_TOKEN
  skip_cleanup: true
  on:
    tags: true
