sudo: required
language: minimal
dist: xenial
script:
# - make tests
  - echo "Hello world"
before_deploy:
- curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
- "mv \$HOME/.poetry/bin/poetry /usr/bin/poetry"
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  #   on:
  #     tags: true
env:
  global:
  - secure: CEMUaMOU4PaYkIlO+mHkBL4z0SP8oT7DKhnG0BuXPPUKZzRGMXb1iHbRWH9fiYBFB/2lTEDJ9+qcvq5VVHkB452LrdHpISCgHHjKde/efGvXWDnCRUGubRNNijlkQdMQsmXmsM6I/n3yOEfehQo6L9fYWM4BGkn/41Mo2H9h4491ozgBD870FsA2QN6ac8VYo+z1sIgta/eq8WZUDZUnudTNqyqdGbgs4kYF/bxU10INDUpt8p/K5A/LrTNZrkWUsaUUSBETFvmU0EZ/b3GofK9HgwjWxtYMh0FZdJ62kO8cdm8I154BBKwEGCQKTcP7UJjJ/MVDaibK4tO+7g2e+SrSLAF9oE57xfd8vTss5NBjRYZID4lpuferQ0hyZ16IzNWlvZbIDRDQ3l1NF/C9wx45M9N6PgLhDGouHQptFdlCsyM7FuECnP8c8ayi1b08qDQ/1LDBuf4UHy9uPbMDRGPOJsnLtTUmajVkoazUVfG382HygVa/YlFzAx9xSnuobTe++RBmZEBAn7tRP255Vj2nD276I/ZadESUZz1E6LEzDAi25fRl8kJnDDcf2GBHf2wXfmYOoJrz/WgG7uOydHPOwgEP3S3Ox/1Ssfk9xEsMgxaRZHcJQmC6y2zLFdhMPbdoeZSyM+dX8WEiDBpWijVEgsrCI1nEnr9FJY4gpqs=
  - secure: YinR9W5yDnDvpg1WzLbdNwKlCMQOKuAkKbTQmXRXSIspJocatr9hB9bCcA4K7LYGc9LkKUgrCih6rlPKGxFVbuyYZrk2C191Zt42fSmdwzg04HIEOVdVfOOzQc5UlbXxFCLMZSz5N2gGIyR0O28teyRj95dhH+irvqiQ1PNErwdvw0/pa12cNWljbfxXbueaudnIlWp1ytzQiAr11G0rwG+WtVYQmU/mBFeCeJ5AXe8Ta190DV5JTNugnXzEnxhog9yWlY+7X2RjDkD8+dtH2EFDqW7I8dk6qp404+kIR2D6H9lGw+fegaQXs51iuAnX6llkp3LSl+f2bS40rD7q8IpAomeF8wbAI9cyIG1gYxJuCsAd/t1rjIfsibXnSylVyn0epUiU3ayVRNHRi24ED0z+qgHdEQAjzvqZ8bxebz9Jq/EjMIQKdrQ9m7oMtrK6KF/NZBcXaiuJ9l5+qQWSJ1ewqpKIcnn1SsF1gK8vyWGCWuzf1UjnxlcUkPfSIcdX+bbI3fvQtu20SaGUymNsbSEzwQHou8VQ5lkF+1Ley8Tr+vpRIeGtM1g50B4UKKfu2DjtyliOxmR8l2VflhHau7fXMXEUY4/vVevOjljR3QnAeCAcCbHlP6/jl4ezEIOGKPx42wjjTLXoqwEXVw1goaxAQUUkFCuC+1OeSWL8agY=
